### Register 
POST http://localhost:4005/auth/register
Content-Type: application/json

{
"username": "test@test.com", "password": "1234512345"
}

### Login 
POST http://localhost:4005/auth/login
Content-Type: application/json

{
"username": "test@test.com", "password": "1234512345"
}

### Fetch all todos  
GET http://localhost:4005/todos
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzQxMDUwNzY5LCJleHAiOjE3NDEwNTQzNjl9.VqH4xJS2vnm9BcmuZpuRumL53U6KbZumrCgurrArMbs

### Creates a new  
POST http://localhost:4005/todos
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzQxMDUwNzY5LCJleHAiOjE3NDEwNTQzNjl9.VqH4xJS2vnm9BcmuZpuRumL53U6KbZumrCgurrArMbs

{
"task": "Finish coding the projects"
}

### Update a todo  
PUT http://localhost:4005/todos/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzQxMDUwNzY5LCJleHAiOjE3NDEwNTQzNjl9.VqH4xJS2vnm9BcmuZpuRumL53U6KbZumrCgurrArMbs

{
"completed": 1
}

### Delete a todo  
DELETE http://localhost:4005/todos/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzQxMDUwNzY5LCJleHAiOjE3NDEwNTQzNjl9.VqH4xJS2vnm9BcmuZpuRumL53U6KbZumrCgurrArMbs
